### ISSUE TITLE
Recomendaciones para aplicar principios SOLID

### ISSUE THREAD

**Issue by maalloor** [tavo1987/Gym#1]
-
En la clase Fecha no se cumple el principio de open-closed (OPC) y en parte el principio de responsabilidad simple (SRP), ya que la clase Fecha además de encargarse de la recepción del día, mes y año, se está encargando de la creación del formato de dichas fechas a fecha latina y fecha europea. ¿Y si se requiere presentar la fecha en el formato asiático, africano, o algún país que tiene su propio formato de fecha? Si seguimos para haciendo métodos por cada formato de fecha, sobrecargaríamos aún más la clase. Para cumplir con OCP y SRP en la clase Fecha se propuso crear el método abstracto getFecha () para que pueda ser sobrescrito en las clases hijas de la clase Fecha, así podremos crear tantas clases de acuerdo al formato de fecha de un determinado continente o país. De esta manera, hacemos que el código sea abierto a extensiones y cerrado modificaciones.

- Rediseño Clase Fecha 
![image](https://user-images.githubusercontent.com/66036423/88002895-3256ad80-cac9-11ea-9183-f72be64c667c.png)

- Nueva clase: FechaLatina
![image](https://user-images.githubusercontent.com/66036423/88002918-426e8d00-cac9-11ea-8796-6901d5cb286f.png)

- Nueva clase: FechaEuropea
![image](https://user-images.githubusercontent.com/66036423/88002943-52866c80-cac9-11ea-8e5e-ce404e5fe994.png)

* Diagrama: Rediseño clase Fechas
![image](https://user-images.githubusercontent.com/66036423/88005923-173b6c00-cad0-11ea-8d29-42bcbd935838.png)

-
Por otra parte, la clase Foto está dependiendo de una clase de bajo nivel que se encarga de conectar el programa con la base de datos SQL, la cual se está instanciando en el constructor de la clase Foto y utilizando posteriormente. Para que clase Foto cumpla con el principio de dependencia inversa (DIP), como primer paso debemos depender de abstracciones en lugar de elementos concretos.

- Interfaz ConexionInterface
![image](https://user-images.githubusercontent.com/66036423/88002111-57e2b780-cac7-11ea-9974-8948e303fa8b.png)

- Clase Conexión
![image](https://user-images.githubusercontent.com/66036423/88002217-98dacc00-cac7-11ea-87ba-58acc385cd95.png)

De esta forma estamos adicionando una capa de abstracción a nuestra aplicación, la cual nos permite depender únicamente de la interfaz en lugar de su implementación concreta. Posteriormente, debemos evitar crear las clases concretas en el constructor de la clase Foto de tal manera que estas sean pasadas desde el constructor.

- Implementación en la clase Foto
![image](https://user-images.githubusercontent.com/66036423/88002284-caec2e00-cac7-11ea-980b-736b6c440cf7.png)

* Diagrama: Rediseño clase Foto
![image](https://user-images.githubusercontent.com/66036423/88005192-66809d00-cace-11ea-81df-e9e7441258aa.png)

-
Las clases Cliente, Pagos, Membresia y Ficha tienen responsabilidades que no les corresponde, ya que esas clases solo se encargan del manejo de información, pero también se las esta haciendo responsable de buscar, eliminar, actualizar o agregar información en la base de datos. Por tanto, para cumplir con el principio de responsabilidad simple (SRP), debe crear clases adicionales para que contengan las operaciones que se deben realizar en la base de datos.

* Clases para operaciones
- Clase Cliente

![image](https://user-images.githubusercontent.com/66036423/88009014-2245ca80-cad7-11ea-9189-e077945bcf7c.png)
![image](https://user-images.githubusercontent.com/66036423/88009037-2a056f00-cad7-11ea-97dd-af106dbd7a5b.png)
![image](https://user-images.githubusercontent.com/66036423/88009047-31c51380-cad7-11ea-934a-ca4c435c4176.png)

- Clase PagoOP

![image](https://user-images.githubusercontent.com/66036423/88008957-017d7500-cad7-11ea-80d9-fddfbb926ac5.png)
![image](https://user-images.githubusercontent.com/66036423/88008976-080bec80-cad7-11ea-9f1b-6044447c4f00.png)

- Clase MembresiaOP

![image](https://user-images.githubusercontent.com/66036423/88008876-cf6c1300-cad6-11ea-8644-45fee4df2ece.png)
![image](https://user-images.githubusercontent.com/66036423/88008938-f3c7ef80-cad6-11ea-860f-1acccd1c52cb.png)

* Diagrama: Rediseño clase Cliente
![image](https://user-images.githubusercontent.com/66036423/88007396-86ff2600-cad3-11ea-9e11-bc90e8e49e92.png)

* Diagrama: Rediseño clase Pagos
![image](https://user-images.githubusercontent.com/66036423/88008031-ec074b80-cad4-11ea-9d11-3c1d8f68f932.png)

* Diagrama: Rediseño clase Membresia
![image](https://user-images.githubusercontent.com/66036423/88008684-7a300180-cad6-11ea-906e-706aab0e900e.png)

**Comment by tavo1987** [comment]
@maalloor, este proyecto es solo algo que hice para un trabajo de fin de una materia, es decir, no es nada recomendable usarlo para produción, ya que no tenía la experiencia necesaria y peor aún sabía de la existencias de los principios SOLID 😄, Por otro lado, no tengo intenciones de mantener este código. Si quieres mejorarlo puedes enviarme un pull request haciendo las mejoras que mencionas.

Saludos.
